// src/lib/quote-html.js
//
// Real HTML-template rendering for TakeoffX/PropX quotes and proposals -
// generateQuoteHtml() plus its private rendering helpers (rgbToHex,
// fmtCurrency, buildLineItems, renderHeader/Separator/BillTo/
// EstimateDetails/LineItemsTable/Totals/Acceptance/Terms/AddendumPages).
// Extracted 2026-09-10 from legacy-monolith.js (previously inline,
// ~143990-144764, including DEFAULT_THEME_CONFIG - a real dependency my
// first pass missed with a call-only grep, since it's referenced as a
// bare value, not a function call; caught on the first real test run
// instead of assumed away). Confirmed self-contained via a real grep pass over
// every function call in the block: every helper here is called only
// from within this same block, except esc()/fmtDate(), which had real
// fan-out elsewhere in legacy-monolith.js - those two now live in the
// genuinely shared src/lib/html-format.js instead, imported by both
// this file and legacy-monolith.js's other call sites.
//
// This is the module registerDocumentGeneratorRoutes()
// (src/routes/document-generators.js) receives generateQuoteHtml as an
// injected dependency for - see that file's own header comment for why
// it's passed in rather than imported directly (avoids a circular
// import while legacy-monolith.js is still the caller).

import { esc, fmtDate } from "./html-format.js";

var DEFAULT_THEME_CONFIG = {
  version: "1.0",
  palette: {
    primary: [0.2, 0.2, 0.2],
    accent: [0.2, 0.2, 0.2],
    text: [0.33, 0.33, 0.33],
    muted: [0.6, 0.6, 0.6],
    border: [0.85, 0.85, 0.85],
    background: [0.96, 0.96, 0.96]
  },
  header: {
    title_text: "ESTIMATE",
    title_size: 20,
    title_position: "top-left",
    company_name_size: 11,
    company_detail_size: 9,
    logo_position: "top-right",
    logo_max_dim: 80,
    separator: "bar",
    separator_thickness: 2
  },
  bill_to: {
    enabled: true,
    background: true,
    label: "Bill to",
    width_pct: 0.55
  },
  estimate_details: {
    enabled: true,
    separator: "dotted",
    fields: ["estimate_no", "estimate_date", "validity"]
  },
  table: {
    style: "flat",
    columns: [
      { key: "num", header: "#", width: 30, align: "left" },
      { key: "product", header: "Product or service", width: 150, align: "left", bold: true },
      { key: "description", header: "Description", width: "flex", align: "left" },
      { key: "qty", header: "Qty", width: 45, align: "right" },
      { key: "rate", header: "Rate", width: 65, align: "right" },
      { key: "amount", header: "Amount", width: 75, align: "right" }
    ],
    header_border: true,
    header_bg: false,
    row_border_color: [0.85, 0.85, 0.85],
    category_rows: true,
    category_bg: [0.96, 0.96, 0.96]
  },
  totals: {
    position: "right",
    separator: "dotted",
    total_size: 14,
    label_size: 9
  },
  acceptance: {
    enabled: true,
    fields: ["accepted_date", "accepted_by"]
  },
  footer: {
    text: "Generated by {company_name} via Weyland by Weyland",
    size: 8,
    position: "center"
  }
};

function rgbToHex(arr) {
  if (!arr || arr.length < 3)
    return "#333333";
  return "#" + arr.map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("");
}
function fmtCurrency(val) {
  const num = Number(val) || 0;
  return "$" + num.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
function buildLineItems(hardwareSets, doors, frames, services) {
  const allItems = [];
  let itemNum = 0;
  if (hardwareSets.length > 0) {
    allItems.push({ type: "category", label: "HARDWARE" });
    for (const s of hardwareSets) {
      itemNum++;
      const comps = s.components || [];
      const description = `${comps.length} component${comps.length !== 1 ? "s" : ""}, ${s.door_count || 0} door${(s.door_count || 0) !== 1 ? "s" : ""}`;
      allItems.push({
        type: "item",
        num: itemNum,
        product: s.set_name || `HW Set ${s.set_number || itemNum}`,
        description,
        qty: s.door_count || 1,
        rate: s.set_unit_price || 0,
        amount: s.line_total || 0
      });
    }
  }
  if (doors.length > 0) {
    allItems.push({ type: "category", label: "DOORS" });
    for (const d of doors) {
      itemNum++;
      const productCode = [d.door_type || d.type, d.material].filter(Boolean).join(" ") || d.description || "Door";
      const desc = [d.size, d.fire_rating ? `FR: ${d.fire_rating}` : null].filter(Boolean).join("  ");
      allItems.push({
        type: "item",
        num: itemNum,
        product: productCode,
        description: desc || d.notes || "",
        qty: d.quantity || 0,
        rate: d.unit_price || 0,
        amount: (d.quantity || 0) * (d.unit_price || 0)
      });
    }
  }
  if (frames.length > 0) {
    allItems.push({ type: "category", label: "FRAMES" });
    for (const f of frames) {
      itemNum++;
      const productCode = [f.frame_type || f.type, f.material].filter(Boolean).join(" ") || f.description || "Frame";
      const desc = [f.size, f.fire_rating ? `FR: ${f.fire_rating}` : null].filter(Boolean).join("  ");
      allItems.push({
        type: "item",
        num: itemNum,
        product: productCode,
        description: desc || f.notes || "",
        qty: f.quantity || 0,
        rate: f.unit_price || 0,
        amount: (f.quantity || 0) * (f.unit_price || 0)
      });
    }
  }
  if (services.length > 0) {
    allItems.push({ type: "category", label: "SERVICES" });
    for (const s of services) {
      itemNum++;
      allItems.push({
        type: "item",
        num: itemNum,
        product: s.description || "Service",
        description: s.notes || "",
        qty: s.quantity || 0,
        rate: s.unit_price || 0,
        amount: (s.quantity || 0) * (s.unit_price || 0)
      });
    }
  }
  return allItems;
}
export function generateQuoteHtml(quoteData, logoDataUri = null) {
  const theme = quoteData.templateDna || DEFAULT_THEME_CONFIG;
  const {
    vendor = {},
    recipient = {},
    quoteNumber,
    quoteDate,
    validityDays = 30,
    hardwareSets = [],
    doors = [],
    frames = [],
    services = [],
    totals = {},
    settings = {},
    coverNote = null
  } = quoteData;
  const p = theme.palette || DEFAULT_THEME_CONFIG.palette;
  const colors = {
    primary: rgbToHex(p.primary),
    accent: rgbToHex(p.accent || p.primary),
    text: rgbToHex(p.text),
    muted: rgbToHex(p.muted),
    border: rgbToHex(p.border),
    background: rgbToHex(p.background)
  };
  const hdr = theme.header || DEFAULT_THEME_CONFIG.header;
  const billTo = theme.bill_to || DEFAULT_THEME_CONFIG.bill_to;
  const estDet = theme.estimate_details || DEFAULT_THEME_CONFIG.estimate_details;
  const tbl = theme.table || DEFAULT_THEME_CONFIG.table;
  const tot = theme.totals || DEFAULT_THEME_CONFIG.totals;
  const acc = theme.acceptance || DEFAULT_THEME_CONFIG.acceptance;
  const ftr = theme.footer || DEFAULT_THEME_CONFIG.footer;
  const allItems = buildLineItems(hardwareSets, doors, frames, services);
  const categoryBg = rgbToHex(tbl.category_bg || p.background);
  const rowBorderColor = rgbToHex(tbl.row_border_color || p.border);
  const footerText = (ftr.text || "").replace("{company_name}", vendor.company_name || "Weyland");
  const validUntil = quoteDate ? (() => {
    const d = new Date(quoteDate);
    d.setDate(d.getDate() + (validityDays || 30));
    return fmtDate(d.toISOString());
  })() : "\u2014";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(hdr.title_text)} #${quoteNumber || ""} \u2014 ${esc(vendor.company_name || "Quote")}</title>
  <style>
    /* ---- CSS Custom Properties from Theme Config ---- */
    :root {
      --color-primary: ${colors.primary};
      --color-accent: ${colors.accent};
      --color-text: ${colors.text};
      --color-muted: ${colors.muted};
      --color-border: ${colors.border};
      --color-background: ${colors.background};
      --font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    }

    /* ---- Reset & Base ---- */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: var(--font-family);
      font-size: 10pt;
      color: var(--color-text);
      background: #fff;
      line-height: 1.4;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .quote-page {
      max-width: 8.5in;
      margin: 0 auto;
      padding: 0.69in;
      position: relative;
      min-height: 11in;
    }

    /* ---- @media print ---- */
    @media print {
      @page {
        size: Letter;
        margin: 0.69in;
      }
      body { background: none; }
      .quote-page {
        max-width: none;
        padding: 0;
        margin: 0;
      }
      .no-print { display: none !important; }
    }

    /* ---- Header ---- */
    .quote-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 6pt;
    }
    .quote-header-left { flex: 1; }
    .quote-header-right {
      flex-shrink: 0;
      text-align: right;
    }
    .quote-title {
      font-size: ${hdr.title_size || 20}pt;
      font-weight: 700;
      color: var(--color-primary);
      letter-spacing: 0.5pt;
      margin-bottom: 4pt;
    }
    .company-name {
      font-size: ${hdr.company_name_size || 11}pt;
      font-weight: 700;
      color: var(--color-primary);
      margin-bottom: 2pt;
    }
    .company-detail {
      font-size: ${hdr.company_detail_size || 9}pt;
      color: var(--color-text);
      margin-bottom: 1pt;
    }
    .company-logo {
      max-width: ${hdr.logo_max_dim || 80}px;
      max-height: ${hdr.logo_max_dim || 80}px;
      object-fit: contain;
    }

    /* Separator */
    .separator-bar {
      height: ${hdr.separator_thickness || 2}pt;
      background: var(--color-primary);
      margin: 8pt 0 14pt 0;
    }
    .separator-line {
      border-top: 1pt solid var(--color-primary);
      margin: 8pt 0 14pt 0;
    }
    .separator-dotted {
      border-top: 1pt dotted var(--color-muted);
      margin: 8pt 0 14pt 0;
    }

    /* ---- Bill-to Section ---- */
    .bill-to-section {
      ${billTo.background ? `background: var(--color-background);` : ""}
      padding: 10pt 12pt;
      margin-bottom: 14pt;
      width: ${(billTo.width_pct || 0.55) * 100}%;
    }
    .bill-to-label {
      font-size: 9pt;
      color: var(--color-muted);
      text-transform: uppercase;
      letter-spacing: 0.5pt;
      margin-bottom: 4pt;
    }
    .bill-to-name {
      font-size: 11pt;
      font-weight: 700;
      color: var(--color-primary);
      margin-bottom: 2pt;
    }
    .bill-to-detail {
      font-size: 9pt;
      color: var(--color-text);
      margin-bottom: 1pt;
    }

    /* ---- Estimate Details ---- */
    .estimate-details {
      margin-bottom: 16pt;
    }
    .estimate-details-row {
      display: flex;
      justify-content: flex-start;
      gap: 32pt;
      margin-bottom: 4pt;
    }
    .detail-item {
      display: flex;
      flex-direction: column;
    }
    .detail-label {
      font-size: 8pt;
      color: var(--color-muted);
      text-transform: uppercase;
      letter-spacing: 0.3pt;
    }
    .detail-value {
      font-size: 10pt;
      color: var(--color-primary);
      font-weight: 600;
    }

    /* ---- Line Items Table ---- */
    .line-items-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16pt;
      font-size: 9pt;
    }
    .line-items-table thead th {
      font-size: 9pt;
      font-weight: 700;
      color: var(--color-primary);
      padding: 6pt 4pt;
      ${tbl.header_border ? `border-bottom: 1.5pt solid var(--color-primary);` : ""}
      ${tbl.header_bg ? `background: var(--color-background);` : ""}
    }
    .line-items-table tbody td {
      padding: 5pt 4pt;
      border-bottom: 0.5pt solid ${rowBorderColor};
      vertical-align: top;
      font-size: 9pt;
    }
    .line-items-table .align-right { text-align: right; }
    .line-items-table .align-left { text-align: left; }
    .line-items-table .bold-cell { font-weight: 700; }

    /* Category rows */
    .category-row td {
      background: ${categoryBg};
      font-weight: 700;
      font-size: 9pt;
      color: var(--color-primary);
      padding: 5pt 4pt;
      border-bottom: none;
      letter-spacing: 0.3pt;
    }

    /* ---- Totals ---- */
    .totals-section {
      display: flex;
      justify-content: ${tot.position === "center" ? "center" : "flex-end"};
      margin-bottom: 20pt;
    }
    .totals-table {
      min-width: 220pt;
    }
    .totals-table .totals-sep {
      border-top: 1pt ${tot.separator === "dotted" ? "dotted" : tot.separator === "line" ? "solid" : "dotted"} var(--color-border);
      padding-top: 4pt;
      margin-top: 4pt;
    }
    .totals-row {
      display: flex;
      justify-content: space-between;
      padding: 3pt 0;
    }
    .totals-label {
      font-size: ${tot.label_size || 9}pt;
      color: var(--color-muted);
    }
    .totals-value {
      font-size: ${tot.label_size || 9}pt;
      color: var(--color-text);
      font-weight: 600;
    }
    .totals-grand .totals-label,
    .totals-grand .totals-value {
      font-size: ${tot.total_size || 14}pt;
      color: var(--color-primary);
      font-weight: 700;
    }

    /* ---- Acceptance ---- */
    .acceptance-section {
      margin-bottom: 20pt;
      padding-top: 16pt;
      border-top: 1pt dotted var(--color-border);
    }
    .acceptance-row {
      display: flex;
      gap: 40pt;
      margin-top: 24pt;
    }
    .acceptance-field {
      flex: 1;
    }
    .acceptance-line {
      border-bottom: 1pt solid var(--color-border);
      min-height: 20pt;
      margin-bottom: 4pt;
    }
    .acceptance-field-label {
      font-size: 8pt;
      color: var(--color-muted);
    }

    /* ---- Terms ---- */
    .terms-section {
      margin-bottom: 20pt;
      padding-top: 12pt;
    }
    .terms-title {
      font-size: 9pt;
      font-weight: 700;
      color: var(--color-primary);
      margin-bottom: 4pt;
    }
    .terms-text {
      font-size: 8pt;
      color: var(--color-muted);
      line-height: 1.5;
    }

    /* ---- Footer ---- */
    .quote-footer {
      text-align: ${ftr.position || "center"};
      font-size: ${ftr.size || 8}pt;
      color: var(--color-muted);
      padding-top: 12pt;
      border-top: 0.5pt solid var(--color-border);
      position: absolute;
      bottom: 0.69in;
      left: 0.69in;
      right: 0.69in;
    }
    @media print {
      .quote-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
      }
    }
  </style>
</head>
<body>
  <div class="quote-page">
${renderHeader(hdr, vendor, logoDataUri, colors)}
${renderSeparator(hdr.separator)}
${billTo.enabled !== false ? renderBillTo(billTo, recipient) : ""}
${estDet.enabled !== false ? renderEstimateDetails(estDet, quoteNumber, quoteDate, validUntil) : ""}
${coverNote ? `<div class="cover-note" style="margin:14pt 0;padding:10pt 12pt;border-left:2pt solid var(--color-primary);font-size:9.5pt;line-height:1.5;color:var(--color-text)">${esc(coverNote)}</div>` : ""}
${renderLineItemsTable(tbl, allItems, settings)}
${renderTotals(totals, settings)}
${acc.enabled !== false ? renderAcceptance(acc) : ""}
${renderTerms(validityDays, settings)}
    <div class="quote-footer">${esc(footerText)}</div>
  </div>
${settings.include_addendum ? renderAddendumPages(hardwareSets, colors, vendor) : ""}
</body>
</html>`;
}
function renderHeader(hdr, vendor, logoDataUri) {
  const titleAlign = hdr.title_position === "center" ? "text-align:center;" : "";
  const logoHtml = logoDataUri ? `<div class="quote-header-right"><img src="${logoDataUri}" class="company-logo" alt="Company Logo"></div>` : "";
  const leftFirst = hdr.logo_position !== "top-left";
  const companyBlock = `
    <div class="quote-header-left">
      <div class="quote-title" style="${titleAlign}">${esc(hdr.title_text || "ESTIMATE")}</div>
      ${vendor.company_name ? `<div class="company-name">${esc(vendor.company_name)}</div>` : ""}
      ${vendor.company_address ? `<div class="company-detail">${esc(vendor.company_address)}</div>` : ""}
      ${[vendor.company_phone, vendor.company_email].filter(Boolean).length > 0 ? `<div class="company-detail">${esc([vendor.company_phone, vendor.company_email].filter(Boolean).join("  |  "))}</div>` : ""}
    </div>`;
  if (hdr.logo_position === "top-left" && logoDataUri) {
    return `    <div class="quote-header">${logoHtml}${companyBlock}</div>`;
  }
  return `    <div class="quote-header">${companyBlock}${logoHtml}</div>`;
}
function renderSeparator(type) {
  if (type === "bar")
    return '    <div class="separator-bar"></div>';
  if (type === "line")
    return '    <div class="separator-line"></div>';
  if (type === "dotted")
    return '    <div class="separator-dotted"></div>';
  return "";
}
function renderBillTo(cfg, recipient) {
  const name = recipient.billing_name || recipient.client_name;
  const addr = recipient.billing_address || recipient.client_address;
  if (!name && !addr && !recipient.project_name) {
    return "";
  }
  return `
    <div class="bill-to-section">
      <div class="bill-to-label">${esc(cfg.label || "Bill to")}</div>
      ${name ? `<div class="bill-to-name">${esc(name)}</div>` : ""}
      ${addr ? `<div class="bill-to-detail">${esc(addr)}</div>` : ""}
      ${recipient.project_name ? `<div class="bill-to-detail">Project: ${esc(recipient.project_name)}</div>` : ""}
      ${recipient.project_address ? `<div class="bill-to-detail">Project Address: ${esc(recipient.project_address)}</div>` : ""}
      ${recipient.dsa_number ? `<div class="bill-to-detail">DSA No: ${esc(recipient.dsa_number)}</div>` : ""}
      ${recipient.rfp_reference ? `<div class="bill-to-detail">RFP Ref: ${esc(recipient.rfp_reference)}</div>` : ""}
      ${recipient.bid_due_date ? `<div class="bill-to-detail">Bid Due: ${esc(fmtDate(recipient.bid_due_date))}</div>` : ""}
    </div>`;
}
function renderEstimateDetails(cfg, quoteNumber, quoteDate, validUntil) {
  const fields = cfg.fields || ["estimate_no", "estimate_date", "validity"];
  const sep = cfg.separator === "dotted" ? '<div class="separator-dotted"></div>' : cfg.separator === "line" ? '<div class="separator-line"></div>' : "";
  const fieldMap = {
    estimate_no: { label: "Estimate No.", value: quoteNumber ? `#${quoteNumber}` : "\u2014" },
    estimate_date: { label: "Date", value: fmtDate(quoteDate) },
    validity: { label: "Valid Until", value: validUntil }
  };
  const detailItems = fields.map((f) => fieldMap[f] || { label: f, value: "\u2014" }).map((f) => `
        <div class="detail-item">
          <span class="detail-label">${esc(f.label)}</span>
          <span class="detail-value">${esc(f.value)}</span>
        </div>`).join("");
  return `${sep}
    <div class="estimate-details">
      <div class="estimate-details-row">${detailItems}
      </div>
    </div>`;
}
function renderLineItemsTable(tbl, allItems, settings) {
  const cols = tbl.columns || DEFAULT_THEME_CONFIG.table.columns;
  const showUnitPrices = settings.show_unit_prices !== false;
  const showExtPrices = settings.show_extended_prices !== false;
  const headerCells = cols.map((col) => {
    const alignClass = col.align === "right" ? "align-right" : "align-left";
    if (col.key === "rate" && !showUnitPrices || col.key === "amount" && !showExtPrices)
      return "";
    return `<th class="${alignClass}">${esc(col.header)}</th>`;
  }).join("");
  const bodyRows = allItems.map((item) => {
    if (item.type === "category") {
      const visibleCols = cols.filter((c) => {
        if (c.key === "rate" && !showUnitPrices)
          return false;
        if (c.key === "amount" && !showExtPrices)
          return false;
        return true;
      });
      return `      <tr class="category-row"><td colspan="${visibleCols.length}">${esc(item.label)}</td></tr>`;
    }
    const cells = cols.map((col) => {
      if (col.key === "rate" && !showUnitPrices)
        return "";
      if (col.key === "amount" && !showExtPrices)
        return "";
      const alignClass = col.align === "right" ? "align-right" : "align-left";
      const boldClass = col.bold ? " bold-cell" : "";
      let val = "";
      switch (col.key) {
        case "num":
          val = item.num;
          break;
        case "product":
          val = item.product;
          break;
        case "description":
          val = item.description;
          break;
        case "qty":
          val = item.qty;
          break;
        case "rate":
          val = fmtCurrency(item.rate);
          break;
        case "amount":
          val = fmtCurrency(item.amount);
          break;
        default:
          val = item[col.key] || "";
      }
      return `<td class="${alignClass}${boldClass}">${esc(String(val))}</td>`;
    }).join("");
    return `      <tr>${cells}</tr>`;
  }).join("\n");
  return `
    <table class="line-items-table">
      <thead><tr>${headerCells}</tr></thead>
      <tbody>
${bodyRows}
      </tbody>
    </table>`;
}
function renderTotals(totals, settings) {
  const { subtotal = 0, taxRate = 0, taxAmount = 0, grandTotal = 0 } = totals;
  const showTax = taxRate > 0;
  return `
    <div class="totals-section">
      <div class="totals-table">
        <div class="totals-row">
          <span class="totals-label">Subtotal</span>
          <span class="totals-value">${fmtCurrency(subtotal)}</span>
        </div>
${showTax ? `        <div class="totals-row">
          <span class="totals-label">Tax (${(taxRate * 100).toFixed(1)}%)</span>
          <span class="totals-value">${fmtCurrency(taxAmount)}</span>
        </div>` : ""}
        <div class="totals-row totals-grand totals-sep">
          <span class="totals-label">Total</span>
          <span class="totals-value">${fmtCurrency(grandTotal)}</span>
        </div>
      </div>
    </div>`;
}
function renderAcceptance(cfg) {
  const fields = cfg.fields || ["accepted_date", "accepted_by"];
  const fieldHtml = fields.map((f) => {
    const label = f === "accepted_date" ? "Date" : f === "accepted_by" ? "Accepted by" : f === "signature" ? "Signature" : f;
    return `
        <div class="acceptance-field">
          <div class="acceptance-line"></div>
          <div class="acceptance-field-label">${esc(label)}</div>
        </div>`;
  }).join("");
  return `
    <div class="acceptance-section">
      <div class="acceptance-row">${fieldHtml}
      </div>
    </div>`;
}
function renderTerms(validityDays, settings) {
  const parts = [];
  if (validityDays) {
    parts.push(`This estimate is valid for ${validityDays} days from the date of issue.`);
  }
  if (settings.exclusions_text) {
    parts.push(settings.exclusions_text);
  }
  if (settings.tax_jurisdiction) {
    parts.push(`Tax jurisdiction: ${settings.tax_jurisdiction}`);
  }
  if (parts.length === 0)
    return "";
  return `
    <div class="terms-section">
      <div class="terms-title">Terms &amp; Conditions</div>
      <div class="terms-text">${parts.map((p) => esc(p)).join("<br>")}</div>
    </div>`;
}
function renderAddendumPages(hardwareSets, colors, vendor) {
  if (!hardwareSets || hardwareSets.length === 0)
    return "";
  let html = "";
  for (const set of hardwareSets) {
    const comps = set.components || [];
    if (comps.length === 0)
      continue;
    let setSubtotal = 0;
    const compRows = comps.map((comp) => {
      const qty = comp.quantity || 1;
      const price = comp.unit_price || 0;
      const uom = (comp.uom || "EA").toUpperCase();
      let factor = 1;
      if (uom === "PR" || uom === "PAIR")
        factor = 2;
      else if (uom === "SET/3" || uom === "SET3")
        factor = 3;
      const extended = qty * price * factor;
      setSubtotal += extended;
      const sourceLabel = comp.price_source === "user_selected" ? "User-selected" : comp.price_source === "catalog" ? "Catalogue" : comp.price_source === "manual" ? "Manual" : "";
      return `
        <tr>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;">${esc(comp.manufacturer || "\u2014")}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;">${esc(comp.model || comp.catalog_number || "\u2014")}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;">${esc(comp.finish || "\u2014")}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;text-align:center;">${qty}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;text-align:center;">${esc(uom)}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;text-align:right;">${fmtCurrency(price)}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:9pt;text-align:right;">${fmtCurrency(extended)}</td>
          <td style="padding:5pt 4pt;border-bottom:0.5pt solid #e2e8f0;font-size:8pt;color:#64748b;">${sourceLabel}</td>
        </tr>`;
    }).join("");
    html += `
  <div class="quote-page" style="page-break-before:always;">
    <div style="margin-bottom:14pt;">
      <div style="font-size:12pt;font-weight:700;color:${colors.primary};margin-bottom:4pt;">ADDENDUM \u2014 Hardware Detail</div>
      <div style="font-size:10pt;font-weight:600;color:${colors.text};">${esc(set.set_name || "Hardware Set " + (set.set_number || ""))}</div>
      <div style="font-size:9pt;color:${colors.muted};">${comps.length} component${comps.length !== 1 ? "s" : ""} &middot; ${set.door_count || 0} door${(set.door_count || 0) !== 1 ? "s" : ""}</div>
    </div>
    <table style="width:100%;border-collapse:collapse;margin-bottom:16pt;font-size:9pt;">
      <thead>
        <tr>
          <th style="text-align:left;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Make</th>
          <th style="text-align:left;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Model</th>
          <th style="text-align:left;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Finish</th>
          <th style="text-align:center;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Qty</th>
          <th style="text-align:center;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">UOM</th>
          <th style="text-align:right;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Unit Price</th>
          <th style="text-align:right;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Extended</th>
          <th style="text-align:left;padding:6pt 4pt;font-weight:700;color:${colors.primary};border-bottom:1.5pt solid ${colors.primary};">Source</th>
        </tr>
      </thead>
      <tbody>
${compRows}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="6" style="padding:6pt 4pt;font-weight:700;color:${colors.primary};border-top:1pt solid ${colors.primary};text-align:right;">Set Subtotal</td>
          <td style="padding:6pt 4pt;font-weight:700;color:${colors.primary};border-top:1pt solid ${colors.primary};text-align:right;">${fmtCurrency(setSubtotal)}</td>
          <td style="border-top:1pt solid ${colors.primary};"></td>
        </tr>
      </tfoot>
    </table>
    <div style="font-size:8pt;color:${colors.muted};text-align:center;position:absolute;bottom:0.69in;left:0.69in;right:0.69in;border-top:0.5pt solid ${colors.border};padding-top:8pt;">
      ${esc(vendor.company_name || "")} \u2014 Hardware Addendum
    </div>
  </div>`;
  }
  return html;
}
